DELIMITER $$
CREATE PROCEDURE ADD_PROPERTY (
    IN P_LANDLORD_ID INT,
    IN P_STREET VARCHAR(200),
    IN P_CITY VARCHAR(100),
    IN P_ZIP INT,
    IN P_SQFT INT UNSIGNED,
    IN P_RENT_COST INT,
    IN P_PROPERTY_RATING FLOAT(2,1),
    IN P_BEDS SMALLINT,
    IN P_BATHROOMS SMALLINT,
    IN P_APT_NUM INT,
    IN P_CAN_RENT BOOL,

    OUT P_PROPERTY_ID INT
)
BEGIN
	DECLARE V_ADDR_ID BIGINT;
    SET V_ADDR_ID = LAST_INSERT_ID();
    
    IF (SELECT COUNT(*) FROM LANDLORD WHERE USER_ID = P_LANDLORD_ID) = 0 
    THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Landlord does not exist';
    END IF;
    
    
    INSERT INTO ADDRESS (STREET, CITY, ZIPCODE)
    VALUES (P_STREET, P_CITY, P_ZIP);
   
	INSERT INTO PROPERTY (
        RENT_COST, PROPERTY_RATING, LANDLORD_ID, BATHROOMS, BEDS, CAN_RENT, APT_NUM, SQFT
    ) VALUES (
        P_RENT_COST, P_PROPERTY_RATING, P_LANDLORD_ID, P_BATHROOMS, P_BEDS, P_CAN_RENT, P_APT_NUM, P_SQFT
    );
   
	SET P_PROPERTY_ID = LAST_INSERT_ID();
END$$
DELIMITER ;
    
    
    
