CREATE TABLE HAS_PREFERENCE (
    USER_ID INT UNSIGNED PRIMARY KEY,
    PREFERENCE_ID INT UNSIGNED PRIMARY KEY,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID),
    CONSTRAINT FK_PREFERENCE FOREIGN KEY (PREFERENCE_ID)
    REFERENCES RENTER_PREFERENCES (PREFERENCE_ID)
);