CREATE TABLE MATCH(
	MATCH_ID INT UNSIGNED PRIMARY KEY,
    RENTER_ID INT UNSIGNED PRIMARY KEY, 
    
	CONSTRAINT FK_USER1
    FOREIGN KEY (RENTER_ID) REFERENCES RENTER(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    
	CONSTRAINT FK_USER2
    FOREIGN KEY (MATCH_ID) REFERENCES RENTER(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    
    CONSTRAINT ck_um_noself CHECK (MATCH_ID <> RENTER_ID),
    UNIQUE KEY ux_um_pair (pair_a, pair_b)
)