CREATE TABLE MESSAGE (
    MSG_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    SENDER_ID INT UNSIGNED NOT NULL,
    RECIPIENT_ID INT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MESSAGE_TEXT NVARCHAR(1000) NOT NULL,
    IS_READ BOOL NOT NULL,
    CONSTRAINT FK_MESSAGE_SENDER
		FOREIGN KEY (SENDER_ID) REFERENCES USER (USER_ID),
	CONSTRAINT FK_MESSAGE_RECIPIENT
		FOREIGN KEY (RECIPIENT_ID) REFERENCES USER (USER_ID)
);
    
    
    

	