CREATE TABLE NOTIFICATION (
    NOTIFICATION_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_READ BOOL NOT NULL,
    NOTIFICATION_TEXT NVARCHAR(1000) NOT NULL
);
    
    
	

