CREATE TABLE RENTER_SETTINGS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    DISTANCE_MAX INT NOT NULL,
    GENDER_PREFERRED CHAR(1) NOT NULL,
    CONSTRAINT CHK_GENDER CHECK (GENDER_PREFERRED IN ('M' , 'F', 'X', '?')),
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID)
);