CREATE TABLE REVIEW (
    REVIEW_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    USER_ID INT UNSIGNED NOT NULL,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    COMMENTS VARCHAR(1000),
    STARS TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID),
    FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTY (PROPERTY_ID)
);