CREATE INDEX IDX_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_DISPLAY_NAME ON USERS(DISPLAY_NAME);
CREATE INDEX IDX_BIRTHDATE ON USERS(BIRTH_DATE);

CREATE INDEX IDX_RENT ON PROPERTY(RENT_COST);

CREATE INDEX IDX_NOTIFICATION_TIMESTAMP ON NOTIFICATION(TIME_STAMP);

CREATE INDEX IDX_MESSAGE_TIMESTAMP ON MESSAGE(TIME_STAMP);


CREATE INDEX IDX_CITY ON ADDRESS(CITY);
