
CREATE TABLE IF NOT EXISTS ADDRESS (
	ADDR_ID INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    STREET VARCHAR(200) NOT NULL,
	CITY VARCHAR(100) NOT NULL,
	ZIPCODE INT UNSIGNED NOT NULL,
    PRIMARY KEY (ADDR_ID)
);

CREATE TABLE IF NOT EXISTS USERS (
	USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
   	PASS_WORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER INT NOT NULL,
    GENDER ENUM('male','female','other') DEFAULT 'other',
    USER_DESC NVARCHAR(1000),
    PICTURE_URL NVARCHAR(1000),
    BIRTH_DATE DATE NOT NULL,
    DISPLAY_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS RENTER (
	USER_ID INT UNSIGNED PRIMARY KEY,
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS RENTER_SETTINGS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    DISTANCE_MAX INT NOT NULL,
    GENDER_PREFERRED CHAR(1) NOT NULL,
    CHECK (GENDER_PREFERRED IN ('M' , 'F', 'X', '?')),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);


CREATE TABLE IF NOT EXISTS RENTER_PREFERENCES (
    PREFERENCE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    PREFERENCE_NAME VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS HAS_PREFERENCE (
    USER_ID INT UNSIGNED,
    PREFERENCE_ID INT UNSIGNED PRIMARY KEY,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (PREFERENCE_ID) REFERENCES RENTER_PREFERENCES (PREFERENCE_ID)
);

CREATE TABLE IF NOT EXISTS LANDLORD (
	USER_ID INT UNSIGNED PRIMARY KEY,
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS MESSAGE (
  MSG_ID         INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SENDER_ID      INT UNSIGNED NOT NULL,
  RECIPIENT_ID   INT UNSIGNED NOT NULL,
  SENT_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MESSAGE_TEXTS  VARCHAR(1000) CHARACTER SET utf8mb4 NOT NULL,
  IS_READ        TINYINT(1) NOT NULL DEFAULT 0,

  CONSTRAINT FK_SENDER
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_RECIPIENT
    FOREIGN KEY (RECIPIENT_ID) REFERENCES USERS(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE
    );
    

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    TIME_STAMP TIMESTAMP NOT NULL,
    IS_READ BOOL NOT NULL,
    NOTIFICATION_TEXT NVARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTIFIES (
    NOTIFICATION_ID INT UNSIGNED PRIMARY KEY,
    USER_ID INT UNSIGNED,
    CONSTRAINT FK_NOTIFICATION FOREIGN KEY (NOTIFICATION_ID)
        REFERENCES NOTIFICATION (NOTIFICATION_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_NOTIFIES_USER_ID FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
    
    
CREATE TABLE IF NOT EXISTS PROPERTY (
	PROPERTY_ID INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    RENT_COST INT UNSIGNED NOT NULL,
    PROPERTY_RATING FLOAT(2,1),
    LANDLORD_ID INT UNSIGNED NOT NULL,
    BATHROOMS SMALLINT UNSIGNED NOT NULL,
    BEDS SMALLINT UNSIGNED NOT NULL,
    CAN_RENT BOOL NOT NULL,
    APT_NUM INT UNSIGNED,
    ADDR INT UNSIGNED UNIQUE NOT NULL,
    PRIMARY KEY (PROPERTY_ID),
    FOREIGN KEY (LANDLORD_ID) REFERENCES LANDLORD (USER_ID),
	FOREIGN KEY (ADDR) REFERENCES ADDRESS (ADDR_ID),
    CHECK (PROPERTY_RATING >= 0.0 AND PROPERTY_RATING <= 5.0)
);

CREATE TABLE IF NOT EXISTS REVIEW (
    REVIEW_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT UNSIGNED NOT NULL,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    COMMENTS VARCHAR(1000),
    STARS FLOAT(2 , 1 ) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY (PROPERTY_ID)
);


CREATE TABLE IF NOT EXISTS RENTER_MATCH (
    MATCH_ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    RENTER_A_ID INT UNSIGNED,
    RENTER_B_ID INT UNSIGNED,
    
    CONSTRAINT fk_rm_a FOREIGN KEY (RENTER_A_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_rm_b FOREIGN KEY (RENTER_B_ID)
        REFERENCES USERS(USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY ux_pair (RENTER_A_ID , RENTER_B_ID)
);
