-- TITLE: SEND_MESSAGE
-- AUTHOR: SOPHIA PRIOLA 
-- MESSAGE SEND PROCEDURE BETWEEN TWO USERS
-- THERE CANNOT BE MULTIPLE USERS IN MESSAGE THREADS

DELIMITER $$

CREATE PROCEDURE SEND_MESSAGE(
    IN p_SENDER_ID    INT,
    IN p_RECIPIENT_ID INT,
    IN p_MESSAGE_TEXT VARCHAR(1000)
)
BEGIN
    -- Insert a new "text message" as unread (IS_READ = 0)
    INSERT INTO MESSAGE (
        SENDER_ID, 
        RECIPIENT_ID, 
        SENT_TIMESTAMP, 
        MESSAGE_TEXT, 
        IS_READ
    )
    VALUES (
        p_SENDER_ID, 
        p_RECIPIENT_ID, 
        CURRENT_TIMESTAMP, 
        p_MESSAGE_TEXT, 
        0
    );
END $$
DELIMITER ;


