-- TITLE: SEND_NOTIFICATION.sql
-- AUTHOR: SOPHIA PRIOLA
-- SEND_NOTIFICATION Is a procedure to send system wide notifications to users 
-- Insert a new unread notification with the current timestamp and given text

DELIMITER $$

CREATE PROCEDURE SEND_NOTIFICATION (
  -- Variables in use 
  IN  p_TEXT  VARCHAR(1000)
)
  
BEGIN
  INSERT INTO NOTIFICATION (TIME_STAMP, IS_READ, NOTIFICATION_TEXT)
  -- SET TIMESTAMP TO "NOW", NEW NOTIFICATIONS START AS UNREAD USE THE TEXT PASSED INTO THE PROCEDURE
  VALUES (CURRENT_TIMESTAMP, 0, p_TEXT);
  
END$$

DELIMITER ;
