-- TITLE: SUBMIT_REVIEW.sql
-- AUTHOR: SOPHIA PRIOLA 
-- SUBMIT_REVIEW IS A PROCEDURE THAT ALLOWS USERS TO SUBMIT REVIEWS IN TERMS
-- OF PROPERTIES THEY HAVE PREVIOUSLY RENTED
-- USERS CAN RANK PROPERTIES OUT OF 5 STARS AND ADD COMMENTS 

DELIMITER $$

CREATE PROCEDURE SUBMIT_REVIEW(
	-- Variables included 
	IN p_USER_ID INT UNSIGNED ,
	IN p_PROPERTY_ID INT UNSIGNED , 
    IN p_COMMENT VARCHAR(1000) , 
    IN p_STARS FLOAT(2,1) UNSIGNED
    )
BEGIN 
	-- INSERT VALUES INTO 
    INSERT INTO REVIEW(USER_ID, PROPERTY_ID, COMMENT, STARS)
    VALUES (p_USER_ID, p_PROPERTY_ID, p_COMMENT, p_STARS);
END$$
    
DELIMITER ;

    
    
    
