-- TITLE: UPDATE_PROPERTY_RATING
-- AUTHOR: SOPHIA PRIOLA
-- WHENEVER A NEW REVIEW IS INSERTED, THIS TRIGGER RECALCULATES THE AVG STAR RATING 
-- AND UPDATES PROPERTY RATING

CREATE TRIGGER UPDATE_PROPERTY_RATING
AFTER INSERT ON REVIEW
FOR EACH ROW        -- Execute once for each inserted review row
UPDATE PROPERTY
SET PROPERTY_RATING = (        -- Recompute the properties avg rating 
    SELECT AVG(STARS)
    FROM REVIEW
    WHERE PROPERTY_ID = NEW.PROPERTY_ID
)
WHERE PROPERTY_ID = NEW.PROPERTY_ID;    -- update the matching PROPERTY row
