-- TITLE: UPDATE_PROPERTY_RATING
-- AUTHOR: SOPHIA PRIOLA
-- WHENEVER A NEW REVIEW IS INSERTED, THIS TRIGGER RECALCULATES THE AVG STAR RATING 
-- AND UPDATES PROPERTY RATING

CREATE TRIGGER UPDATE_PROPERTY_RATING
AFTER INSERT ON REVIEW
FOR EACH ROW
UPDATE PROPERTY
SET PROPERTY_RATING = (
    SELECT AVG(STARS)
    FROM REVIEW
    WHERE PROPERTY_ID = NEW.PROPERTY_ID
)
WHERE PROPERTY_ID = NEW.PROPERTY_ID;
