CREATE PROCEDURE INSERT_USER
    -- Variables to be included
    @USER_ID INT UNSIGNED,
    @USERNAME VARCHAR(50),
   	@PASS_WORD VARCHAR(50),
	@EMAIL VARCHAR(100)
    @PHONE_NUMBER INT,
    @GENDER CHAR(1),
    @BIRTH_DATE DATE,
    @DISPLAY_NAME VARCHAR(200),
AS
BEGIN
    -- Inserting values
    INSERT INTO USERS (USER_ID, USERNAME, PASS_WORD, EMAIL, PHONE_NUMBER, GENDER, BIRTH_DATE, DISPLAY_NAME)
    VALUES (@USER_ID, @USERNAME, @PASS_WORD, @EMAIL, @PHONE_NUMBER, @GENDER, @BIRTH_DATE, @DISPLAY_NAME);
END
