CREATE TABLE IF NOT EXISTS SESSION (
  SESSION_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  USER_ID INT UNSIGNED NOT NULL,
  TOKEN VARCHAR(128) NOT NULL UNIQUE,
  EXPIRES_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL,
  FOREIGN KEY (USER_ID)
  REFERENCES USER (USER_ID)
)