-- TITLE: MESSAGE.sql
-- AUTHOR: SOPHIA PRIOLA
-- TABLE CREATION FOR MESSAGE 
CREATE TABLE IF NOT EXISTS MESSAGE (
	MSG_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	SENDER_ID INT UNSIGNED NOT NULL,
	RECIPIENT_ID INT UNSIGNED NOT NULL,
	TIME_STAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MESSAGE_TEXTS VARCHAR(1000) CHARACTER SET utf8mb4 NOT NULL,
	IS_READ TINYINT(1) NOT NULL DEFAULT 0,
	FOREIGN KEY (SENDER_ID) 
		REFERENCES USERS(USER_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (RECIPIENT_ID) 
		REFERENCES USERS(USER_ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);
