CREATE TABLE NOTIFICATION (
    NOTIFICATION_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    TIME_STAMP TIMESTAMP NOT NULL,
    IS_READ TINYINT(1) DEFAULT 0 NOT NULL,
    NOTIFICATION_TEXT NVARCHAR(1000) NOT NULL
);
    
    
	

