-- TITLE NOTIFICATION.sql
-- AUTHOR: SOPHIA PRIOLA
-- TABLE CREATION FOR NOTIFICATION
CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    TIME_STAMP TIMESTAMP NOT NULL,
    IS_READ TINYINT(1) NOT NULL DEFAULT 0,
    NOTIFICATION_TEXT NVARCHAR(1000) NOT NULL
);
