-- TITLE: REVIEW.sql
-- AUTHOR: SOPHIA PRIOLA
-- TABLE CREATION OF REVIEW 

CREATE TABLE IF NOT EXISTS REVIEW (
    USER_ID INT UNSIGNED PRIMARY KEY,
    PROPERTY_ID INT UNSIGNED PRIMARY KEY,
    COMMENTS VARCHAR(1000),
    STARS FLOAT(2, 1) UNSIGNED NOT NULL,
    CHECK (STARS BETWEEN 1 AND 5), 
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID),
    FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTY (PROPERTY_ID)
);
